version: '3.8'
services:
  db:
    image: postgres:15
    ports:
      - '${DB_PORT:-5432}:5432'
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-postgres}
      interval: 10s
      timeout: 5s
      retries: 20
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME:-postgres}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    networks:
      - xena-network
volumes:
  db_data:
networks:
  xena-network:
    external: true
