query SearchAudioFileNode(
  $and: AudioFileNodeQueryInput
  $or: AudioFileNodeQueryInput
  $limit: Int
  $offset: Int
) {
  audioFileNodes(and: $and, or: $or, limit: $limit, offset: $offset) {
    id
    filePath
    fileName
    album
    albumArtist
    artists
    containedTracks
  }
}
