package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	model1 "audio-searcher/api/graph/model"
	"context"
)

// AudioFileNode is the resolver for the audioFileNode field.
func (r *queryResolver) AudioFileNode(ctx context.Context) ([]*model1.AudioFileNode, error) {
	return nil, nil
}
