package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"audio-searcher/api/graph/model"
	"context"
)

// AudioFileNodes is the resolver for the audioFileNodes field.
func (r *queryResolver) AudioFileNodes(ctx context.Context) ([]*model.AudioFileNode, error) {
	return []*model.AudioFileNode{}, nil
}
