name: CI server

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '.github/workflows/ci-server.yaml'
      - 'server/**'
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: server/go.mod

      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53.3
          working-directory: server
          args: '--verbose ./...'

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: server/go.mod

      - name: Run test
        run: go test ./... -v -count=1
        working-directory: server

  fmt:
    name: Format check
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: server/go.mod

      - name: Format
        run: go fmt ./...
        working-directory: server

      - name: Minimize dependencies
        run: go mod tidy
        working-directory: server

      - name: Check diff
        run: git diff --exit-code
        working-directory: server
